//export 'package:fl_component/screens/cart_screen.dart';
export 'package:fl_component/screens/alert_screen.dart';
export 'package:fl_component/screens/animated_screen.dart';
export 'package:fl_component/screens/avatar_screen.dart';
export 'package:fl_component/screens/home_screen.dart';
export 'package:fl_component/screens/input_screen.dart';
export 'package:fl_component/screens/listview1_screen.dart';
export 'package:fl_component/screens/listview2_screen.dart';
export 'package:fl_component/screens/slider_screen.dart';
